### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Glal488** [silverlight6/TFTMuZeroAgent#1]
It keeps spamming mcts child..etc
Not working for me

**Comment by silverlight6** [comment]
> It keeps spamming mcts child..etc Not working for me

Sorry, I pushed a version with a couple print statements for someone else to help them with debugging. The print statements are in the MCTS agent in the MuZero_Agent_2. Comment them out and you should be fine to train. I'll have a new version pushed tomorrow or whenever without those print statements being spammed.
