### ISSUE TITLE
Discord brings me to an "Invalid Invite" webpage upon clicking the invite link in the README

### ISSUE THREAD

**Issue by AntonSax** [silverlight6/TFTMuZeroAgent#75]
The link I'm clicking: https://discord.com/invite/cPKwGU7dbU

The text provided under "Invalid Invite" is
"This invite may be expired, or you might not have permission to join."
Then there is another button to "Continue to Discord"

**Comment by silverlight6** [comment]
The link still worked for me. Let me create a new one for you. Maybe someone else will see this in the future and can use the same link.

https://discord.gg/cPKwGU7dbU

**Comment by AntonSax** [comment]
Your link redirects to the same url as the one above.
Not sure why the invite didn't like me on my PC, but I opened up this thread on my phone the links worked from there.

Anyways, thanks for the quick response.
